### ISSUE TITLE
Feature request: please open source migrator.sh script

### ISSUE THREAD

**Issue by nodens** [joyent/triton#180]
Hi,

From SDC documentation https://docs.joyent.com/private-cloud/instances/compute-nodes, there is "migrator.sh" script that can help migrating instances from a compute node to another.

Although using this script is not supported, it is provided by joyent support.

Could you please consider open sourcing it ?

Cheers,
## 

Clément Hermann

**Comment by themisanthrope** [comment]
+1

Would love to have access to this - doing it manually is a pain.

**Comment by bahamat** [comment]
Related, [RFD 34](https://github.com/joyent/rfd/blob/master/rfd/0034/README.md).

**Comment by themisanthrope** [comment]
Many thanks - I'll keep an eye on it!

**Comment by piaohai** [comment]
+1

**Comment by bahamat** [comment]
sdc-migrate is being added to triton, and is almost ready. That being the case, I'm going to close this.
