### ISSUE TITLE
Feature Request:

### ISSUE THREAD

**Issue by sdmajor** [joyent/triton#182]
I really like what I have seen in regards to Titan with docker integration... considering Joyant SDC is focused on the best in performance I would like to see Joyant following the Mikelangelo movement

"We develop sKVM, an optimised version of KVM, improve the cloud OS OSv, and we implement holistic monitoring and security modules for the cloud."

SDC + SmartOS + sKVM + OSv = big data, high performance computing, and I/O intensive applications in production.

http://www.mikelangelo-project.eu/technology/
http://www.mikelangelo-project.eu/deliverables/deliverable-d2-13/
http://osv.io/
http://www.seastar-project.org/
http://www.scylladb.com/

These projects are being led by the people responsible for KVM, I would love to see Joyant get involved with Mikelangelo because I would rather use Titan and SDC rather than OpenStack.

sKVM is currently being co-developed by IBM, this will revolutionize the IO speeds for VMs and the OSv OS brings the security of a VM with the efficiency of a docker container.

**Comment by chorrell** [comment]
"Joyant"?

:disappointed:

**Comment by pannon** [comment]
@sdmajor you should really read this https://www.joyent.com/blog/vm-native-or-container-native and watch http://containersummit.io/events/sf-2015/videos/going-container-native

And also for big data  https://www.joyent.com/object-storage

I just hope, someone from the EU Horizon 2020 will have some sense and stop wasting TAX money..

**Comment by cheapRoc** [comment]
Thanks for the suggestion, going to close this one since there isn't really an issue here.
