### ISSUE TITLE
SDC (coal) on kvm?

### ISSUE THREAD

**Issue by fire** [joyent/triton#187]
Looking at the latest releases notes for centos 7, nested virtualization is enabled. This fufills one of the criteria mentioned in the virtual box issue. (demoing standalone hypervisor) Is it possible to support kvm?

Note: I'm on Elementary OS (Based on Ubuntu 14.04 and the Ubuntu 15.04 kernel), libvirt is used on both.

**Comment by siepkes** [comment]
@fire I've created pull request joyent/sdc#194 to add KVM support. I've tested it only on Fedora 23 but I would love feedback if it works for you on Ubuntu!

**Comment by gochist** [comment]
I made a PR https://cr.joyent.us/#/c/746/ to add Ubuntu support.

**Comment by cburroughs** [comment]
@siepkes As the original author, it would be great if you could take a look at https://cr.joyent.us/#/c/746/

**Comment by siepkes** [comment]
@cburroughs sure!

@gochist I added a comment to the Gerrit change ( https://cr.joyent.us/#/c/746/ ). I'm interested to hear what you think!

**Comment by gochist** [comment]
@cburroughs @siepkes I updated my humble opinion and change at ( https://cr.joyent.us/#/c/746/ ).

- qcow2 is default image format and added "--use-raw-image" option for developers who prefer disk performance to saving disk space or snapshot function according to @siepkes ' review comment.
- x-data-plane option will be enabled only if it is applicable

**Comment by siepkes** [comment]
@gochist Thanks for your contributions and insights! Good to see the script was useful!
