### ISSUE TITLE
second compute node setup issue

### ISSUE THREAD

**Issue by andrewrothstein** [joyent/triton#204]
Thanks for the setup debugging hints in #201. I'm trying to add in my second node. The server setup fails at the same step....cnapi.execute_agentsetup_script.

Dug into the log files for the cnapi service. these are the last couple lines of the error message.

configured usbkey mountpoint: \"/mnt/usbkey\"
directory \"/mnt/usbkey\" does not exist; creating.
candidate devices: /dev/dsk/c0t0d0p1
fetching mount status for \"/mnt/usbkey\"
fetching mount information for \"/mnt/usbkey\"
\"/mnt/usbkey\" is not mounted.
mounting \"/dev/dsk/c0t0d0p1\" @ \"/mnt/usbkey\".
mount args: -F pcfs -o foldcase,noatime,hidden,clamptime,rw /dev/dsk/c0t0d0p1 /mnt/usbkey
fetching mount status for \"/mnt/usbkey\"
fetching mount information for \"/mnt/usbkey\"
checking marker file...
filesystem is mounted at \"/mnt/usbkey\"
ensuring usb key is not mounted...
configured usbkey mountpoint: \"/mnt/usbkey\"
fetching mount information for \"/mnt/usbkey\"
unmounting usbkey at \"/mnt/usbkey\"
fetching mount information for \"/mnt/usbkey\"
ok, usb key is not mounted.

the node is iPXE booting off of a USB key. the initialization sequence looks like it's doing all the right things in terms of downloading the boot image and booting up smartos. the node shows up in the operations portal. Any suggestions?

Thank! Andrew

**Comment by rmustacc** [comment]
@jclulow can you take a look at this when you have a chance?

**Comment by jclulow** [comment]
@andrewrothstein In #201 I mentioned the `/var/log/agent-setup.log` log file.  Did you happen to get a copy of this when the failure occurred?

**Comment by andrewrothstein** [comment]
@jclulow I'm unable to ssh into the compute node as the root user using the same password as the headnode root user password so I can't see that. That same root pwd doesn't work at the physical console for the node either.

in my attempts to hit every button possible, I saw this:
```
[root@headnode (us-nj-1) ~]# sdc-agents-healthcheck 
80de3d16-cb5b-d911-98d7-14dae9f5445f ur ok
d252dff5-3c7a-0010-9693-00238b174ade provisioner error
d252dff5-3c7a-0010-9693-00238b174ade zonetracker error
d252dff5-3c7a-0010-9693-00238b174ade ur ok
d252dff5-3c7a-0010-9693-00238b174ade heartbeat error
```

not sure if that's related.

**Comment by andrewrothstein** [comment]
I made a change in the BIOS shutting off the "RAID" mode and turning on the "AHCI" mode for the disks. I don't think SmartOS was seeing any disks on the compute node. Made that change and it looks like it's setting up ... slowly.

Thinks the takeaway are to stop buying sh!t hardware from ebay and to have more patience in waiting for the hosts to come on line..

**Comment by rmustacc** [comment]
On 6/1/16 20:49 , Andrew Rothstein wrote:
> @jclulow I'm unable to ssh into the compute node as the root user using the same password as the headnode root user password so I can't see that. That same root pwd doesn't work at the physical console for the node either.

When you're booting a compute node in this way, it won't use the same
root password as the headnode. Instead you have to get the platform
default password which is on the physical usbkey. You can use
`/usbkey/scripts/mount_usb.sh` to mount it and you should see something
in `/mnt/usbkey/private` IIRC.

**Comment by netg5** [comment]
I faced the same issue for the first time the compute node was setup by Admin UI but after reboot it's can't turn up but in kvm console I can see the image has been loaded. Any idea how I can fix this ?
