### ISSUE TITLE
Run sdcadm post-setup cloudapi fails

### ISSUE THREAD

**Issue by wangjing-samsung** [joyent/triton#206]
I am trying to follow https://github.com/joyent/sdc/blob/master/docs/developer-guide/coal-setup.md 

Output of sdcadm post-setup cloudapi:

[root@headnode (coal-1) ~]# sdcadm post-setup cloudapi
Attempt #1 failed with error SDCClientError: updates client error: getaddrinfo ENOTFOUND; caused by Error: getaddrinfo ENOTFOUND. Retrying again in 100 msecs
Attempt #2 failed with error SDCClientError: updates client error: getaddrinfo ENOTFOUND; caused by Error: getaddrinfo ENOTFOUND. Retrying again in 200 msecs

**Comment by rmustacc** [comment]
What's the output of `sdc-healthcheck`?

**Comment by wangjing-samsung** [comment]
[root@headnode (coal-1) ~]# sdc-healthcheck
ZONE                                 STATE           AGENT               STATUS
global                               running         -                   online
assets                               running         -                   online
sapi                                 running         -                   online
binder                               running         -                   online
manatee                              running         -                   online
moray                                running         -                   online
amonredis                            running         -                   online
redis                                running         -                   online
ufds                                 running         -                   online
workflow                             running         -                   online
amon                                 running         -                   online
sdc                                  running         -                   online
papi                                 running         -                   online
napi                                 running         -                   online
rabbitmq                             running         -                   online
imgapi                               running         -                   online
cnapi                                running         -                   online
dhcpd                                running         -                   online
fwapi                                running         -                   online
vmapi                                running         -                   online
ca                                   running         -                   online
mahi                                 running         -                   online
adminui                              running         -                   online
global                               running         ur                  online
global                               running         smartlogin          online

**Comment by choonho** [comment]
I have same problem, and the reason was network connection.
When install cloudapi, headnode have to reach https://updates.joyent.com.
So check the network connections such as proxy.

**Comment by cheapRoc** [comment]
Hello @wangjing-samsung, this issue is a year old and looks like there's a potential answer. Also, you’ll receive a much quicker responses on both the [mailing list and IRC channel](https://github.com/joyent/triton/blob/master/README.md#community).

For now we're going to close this ticket and we can re-open if you're still experiencing the same issue. Good luck!
