### ISSUE TITLE
Publishing images

### ISSUE THREAD

**Issue by foxx** [joyent/triton#209]
(UPDATED)

I'm creating a DCOS image, to be used on Triton Enterprise, however there doesn't seem to be any documentation on how to push this image to your own image repository (e.g. like `images.joyent.com`) or instructions on how to add your custom image server into the dropdown list under the "images" tab.

In situations where you have multiple deployments of Triton, but instead want to use a single image repository so you don't have to manage export/import across multiple datacenters, such a feature would be quite useful.

So far it seems that I'd either have to have some custom scripts for copying images from one DC to another, or to simply dedicate a single DC for image control and then have some sort of CDN sat in front of it.

Still trawling through documentation and source code, but any hints on best practice would be much appreciated

**Comment by bahamat** [comment]
You can use the [AdminImportRemoteImage](https://github.com/joyent/sdc-imgapi/blob/master/docs/index.md#adminimportremoteimage-post-imagesuuidactionimport-remote) API endpoint, either directly or by using `sdc-imgadm import` with the `-S` option to specify the remote imgapi URL.

**Comment by foxx** [comment]
Perfect, that's precisely what I was looking for, thank you!
