### ISSUE TITLE
Add information how to access docker remote API on CoaL

### ISSUE THREAD

**Issue by igorspasic** [joyent/triton#213]
I have installed CoaL, and docker commands work. However, when I want to access Docker remote API from my mac:

    curl --cert $DOCKER_CERT_PATH/cert.pem --key $DOCKER_CERT_PATH/key.pem http://10.88.88.6:2376/images/json --verbose

Ive got... nothing:

```
*   Trying 10.88.88.6...
* Connected to 10.88.88.6 (10.88.88.6) port 2376 (#0)
> GET /images/json HTTP/1.1
> Host: 10.88.88.6:2376
> User-Agent: curl/7.49.1
> Accept: */*
>
```

I haven't seen anywhere in the docs example of access remote API. How to do this?

**Comment by rmustacc** [comment]
Just to confirm, you've already gone through https://docs.joyent.com/private-cloud/install/advanced-configuration and set up docker, right?

**Comment by igorspasic** [comment]
I used docs from GitHub, but on that page I did things from: https://docs.joyent.com/private-cloud/install/advanced-configuration#setup-docker

```
sdcadm post-setup docker
headnode# sdcadm experimental update dockerlogger
```

So `docker` cli is working.

**Comment by twhiteman** [comment]
If the docker cli is working correctly, then this issue may be due to curl itself. See this docker curl issue for example:
https://github.com/docker/docker/issues/16107

Note: I've never been able to use curl to communicate with a docker server on the Mac, though I have used other tools (node.js for example) to connect just fine.

**Comment by igorspasic** [comment]
Ok, maybe `curl` is not working; but docker fails when building images:
```
Sending build context to Docker daemon 5.632 kB
An error occurred trying to connect: Post http://10.88.88.6:2376/v1.24/build?buildargs=%7B%7D&cgroupparent=&cpuperiod=0&cpuquota=0&cpusetcpus=&cpusetmems=&cpushares=0&dockerfile=Dockerfile&labels=%7B%7D&memory=0&memswap=0&rm=1&shmsize=0&t=wedeploy%2Fjdk&ulimits=null: EOF
```

**Comment by twhiteman** [comment]
@igorspasic Quite possibly an issue, though please file a separate issue for that (and please include details, like a Github repository that contains the Dockerfile and files in question - so we can try to reproduce the problem), thanks.

**Comment by askfongjojo** [comment]
@igorspasic - For the `curl` issue, the endpoint should be https, not http. If you are using OS X, you also have to follow these steps to store your key in KeyChain (https://github.com/docker/docker/issues/16107).

With the above changes, remote API should work on your CoaL:
```
$ curl -k --cert test-curl.p12:mysecret https://10.88.88.6:2376/info
{"Architecture":"x86_64","Driver":"sdc","DriverStatus":[["SDCAccount","angela.fong"]],"ExecutionDriver":"sdc-0.3.0","KernelVersion":"3.12.0-1-amd64","LoggingDriver":"json-file","OperatingSystem":"SmartDataCenter","OSType":"linux","Name":"us-south","IndexServerAddress":"https://index.docker.io/v1/","MemoryLimit":true,"SwapLimit":true,"IPv4Forwarding":true,"ID":"163bcd11-b610-421c-921f-dac6db426d01","Containers":0,"Images":2}
```
