### ISSUE TITLE
Can we create multiple portolan instances?

### ISSUE THREAD

**Issue by marcus-sds** [joyent/triton#214]
When I check "https://docs.joyent.com/private-cloud/resilience", the portolan seems to be only one instance. But "https://docs.joyent.com/private-cloud/networks/sdn/architecture" this one shows that we can use many portolan instances. 

How can we create additional portolan instance?

**Comment by melloc** [comment]
@marcus-sds As of [TOOLS-1644](https://smartos.org/bugview/TOOLS-1644), you can now do this. See the [sdcadm documentation](https://github.com/joyent/sdcadm/blob/master/README.md#create-portolan-ha-instances) for instructions on how to do so.
