### ISSUE TITLE
Headnode install script failure

### ISSUE THREAD

**Issue by aboron** [joyent/triton#218]
Happens when installing a headnode for a real domain (example.com) where either a wildcard dns (*.example.com) or , less likely, a host definition for sapi.example.com actually resolves to a web server.

The initial agents install script fails while running postinstall.sh for config-agent due to getting an 404 reply when none is expected.

The log file does not make note of what url curl is trying to pull from, so diagnosis via the logs is somewhat hampered.

Possibly a note in the installation documentation would be enough to avoid the issue.

**Comment by cheapRoc** [comment]
@aboron Thanks for the information. I actually remember having the exact same issue when I installed Triton myself. It took me a little bit to realize the issue with my domain name collision.

I'm going to bring this up with our internal documentation effort and pass along the info. Thanks again for helping out.
