### ISSUE TITLE
Feature Request: Let's Encrypt integration for on-prem installations

### ISSUE THREAD

**Issue by nshalman** [joyent/triton#224]
It would be really nice to be able to stand up a datacenter and have valid certificates be set up and renewed automatically.

Obviously to automate this all services that would use Let's Encrypt certificates would either have to be accessible over the public internet, or at least the DNS records for them would have to be accessible over the internet and controlled by a Triton API (possibly by extending CNS if that would be appropriate.)

**Comment by bahamat** [comment]
[HEAD-2290](https://smartos.org/bugview/HEAD-2290).

**Comment by nshalman** [comment]
Glad to see it's on the radar. I'm closing this one since it's a duplicate of [HEAD-2290](https://smartos.org/bugview/HEAD-2290).
