### ISSUE TITLE
Triton for x64 ?

### ISSUE THREAD

**Issue by labchef** [joyent/triton#225]
Hi ! I've reviewed this technology and found next problems:

SVR4 hypervisor from 90's. x86 platform in 2017 ?
In the standard 32-bit x86 smp kernel, each process can use 3GB of the 4GB address space and 1GB is used by the kernel (shared in the address space of each process). This means that each virtual CPU will spend more resources for the conversion from x86 to x64.

Maybe this isn't bad for x86 containers, but for x64 it's crazy way:
1. My x64 App in container is spending processor time for x86 SVR4 hypervisor emulation.
2. My server x64 CPU is spending processor time for x86 SVR4 hypervisor emulation.

Perhaps this is the slowest solution for x64 containers orchestration.
@misterbisson @Joyent ?﻿

**Comment by bcantrill** [comment]
This is entirely wrong; as `isainfo` will tell you, we support x64 (née amd64), and always have.
