### ISSUE TITLE
Keyboard not working

### ISSUE THREAD

**Issue by dalu** [joyent/triton#227]
An older Xeon E3-1275v2 machine with 32GB RAM and a USB mouse and USB keyboard.
I copy to usb and boot from usb key.

Yes I have read that it apparently has issues with USB3.0.
I plugged it into the USB2.0 port.

Well the problem is, not matter what USB port I plug the keyboard in I can't "press enter".
Meaning I can't install or setup sdc7.

All I can do is reset.
I installed SmartOS previously on this machine and it didn't have this issue.

Motherboard Gigabyte GA-Z77-UD4H
Keyboard some random "revoltec" keyboard.

**Comment by misterbisson** [comment]
It sounds like you're using a vga console, but the default is for serial. Did you change that in the grub menu?

Look for `grub> variable os_console vga` in [the readme](https://github.com/joyent/triton).

**Comment by dalu** [comment]
Thanks for feedback.
I just found that out myself :) I then went and set vga as default on the USB key.
There was an error regarding UFS and /usbkey
They way I see it, it first installs SmartOS then goes on and installs the zones/manifests.
I could've just kept my previous  SmartOS installation and switched to vga console.
The more you know.

Thanks for help :)
