### ISSUE TITLE
Headnode install fails

### ISSUE THREAD

**Issue by DarkBlaez** [joyent/triton#230]
I've tried to install Triton many times on HP Proliant DL360 G5 and a G6. The result is always the same. Vmadmd and config-agent fail resulting in init:default failing. I imagine if this were system specific I'd see different results. This seems to be an installer issue. I see similar issues dating back to 2016. Since I am documenting this install for a blog, what can be done to resolve. So far given the slow usb thumb drive manner of install I've nearly spent countless hours attempting to install, only to come to the realization the installer has issues. This is build 20170511T002134Z

Let me know what options exist to resolve. Would hate to go back to Openstack for something as an installer issue.

Thanks
DB

**Comment by tgross** [comment]
@DarkBlaez you haven't provided much in the way of details here as to what issues you're seeing. You might find that [the mailing list or IRC](https://github.com/joyent/triton/blob/master/README.md#community) are a better fit for this sort of open-ended support request.
