### ISSUE TITLE
HN and CN ssh key

### ISSUE THREAD

**Issue by benjamin-bergia** [joyent/triton#232]
I remember that at the time of sdc6 it was possible to add public keys to the headnode, but I can't find this in the new triton doc.

Is it still possible to add public keys to the authorized_keys of my headnode ? If yes is it possible on the CNs too ?

**Comment by cheapRoc** [comment]
I believe what you're looking for is [documented here](https://docs.joyent.com/sdc6/managing-smartdatacenter-users-and-passwords). Basically, you edit your USB key for additional configuration used during your head node and compute node installation. I'm unsure of any more of particulars but posting over at [joyent/sdc-headnode](https://github.com/joyent/sdc-headnode) should help as well. Hope that helps you out!

**Comment by cheapRoc** [comment]
Apologies, that link is the old one which you probably referenced. Still digging up the new docs but you should be able to edit your USB key's `root.authorized_keys`. Check `/usbkey/config.inc/generic` or `/usbkey/extra/joysetup/node.config` for the configuration.

**Comment by cheapRoc** [comment]
If that doesn't work re-open over at [joyent/sdc-headnode](https://github.com/joyent/sdc-headnode).

**Comment by cheapRoc** [comment]
Also... http://www.perkin.org.uk/posts/smartos-global-zone-tweaks.html

**Comment by benjamin-bergia** [comment]
Ok I will give it a try. Since the CNs are using PXE where is their configuration stored ?

**Comment by cheapRoc** [comment]
@benjamin-bergia Are you performing PXE at boot or on-board PXE? I'm fairly confident PXE at boot uses the USB key configuration as well.

**Comment by benjamin-bergia** [comment]
PXE but unfortunately I have not restarted any CN recently so I haven't be able to check if it works.
