### ISSUE TITLE
So you saying this whole Triton thing is open source?

### ISSUE THREAD

**Issue by abdulhannanali** [joyent/triton#233]

**Comment by davepacheco** [comment]
[Yes](https://www.joyent.com/blog/sdc-and-manta-are-now-open-source).  Are you having trouble finding the source for something?

**Comment by arekinath** [comment]
If you're referring to the fact that this repo doesn't contain the code, the README explains how it works. Triton is spread out across a number of repositories, which have all the actual code (see for example, https://github.com/joyent/sdc-vmapi for one of the core API services). This repo is just a landing point for visitors.

**Comment by abdulhannanali** [comment]
@davepacheco Nop, not really, as it's far beyond my understanding right now. But Joyent is pretty cool company supporting open source in so many ways. Really takes guts to open source the whole cloud. Would love to learn more about inner workings, as I read the blog post you mentioned, and if many components are written in JavaScript maybe I can understand it too.

**Comment by abdulhannanali** [comment]
Thanks for the help @arekinath
