### ISSUE TITLE
When using an internal CA: triton CLI gets 'INVALID_PURPOSE'

### ISSUE THREAD

**Issue by cmacrae** [joyent/triton#239]
Hi guys 👋 

I've been trying to establish my own internal CA for my on-prem deployment of Triton.  
I've installed all my certificates [as per the documentation](https://docs.joyent.com/private-cloud/install/ssl-certs) and have confirmed they're working as expected (using the `openssl` CLI and `curl`).  

However, when I attempted to set up the Triton CLI on my desktop to interact with it, I ran into some problems.  

I set up a new profile by running and following `triton profile create`.  
When asked if I wanted to set up Docker, I answered yes. It errored out with the following:  
```
WARNING: Docker uses authentication via client TLS certificates that do not
support encrypted (passphrase protected) keys or SSH agents. If you continue,
this profile setup will attempt to write a copy of your SSH private key
formatted as an unencrypted TLS certificate in "~/.triton/docker" for use by
the Docker client.

Continue? [y/n] y

Warning: Error determining if CloudAPI "https://cloudapi.triton.cmacr.ae" provides a Docker service:
    SetupError: error pinging CloudAPI <https://cloudapi.triton.cmacr.ae>: unsupported certificate purpose

Set "pantheon" as current profile (because it is your only profile).
```

So, I tried a simple `triton inst ls` and I got the following back:  
```
triton instance ls: error (INVALID_PURPOSE): unsupported certificate purpose
```

Initially I thought this might be to do with the key usage parameters I'd set on my key.  
So, I went and re-issued my certs, enabling all key uses (just to cover all grounds and test). Re-deployed them. But I'm still hitting the same issue.  

I'd really appreciate some help on this! Please do let me know if there's any further information I can provide.  

Thanks in advance 👍

**Comment by arekinath** [comment]
This error is coming from OpenSSL, complaining that some certificate in the validation chain has a purpose set that it doesn't support. Node.js statically links its own version of OpenSSL, so this might be a version issue? If you're happy to provide the certificate chain I'm happy to have a look through it and see if I can tell you which purpose is the problem.

**Comment by cmacrae** [comment]
Hey @arekinath 👋 Thanks for your response.  

Okay, that's interesting. The allowed uses I gave to my cert are as follows:
```
    "digital_signature",
    "data_encipherment",
    "key_agreement",
    "crl_signing",
    "any_extended",
    "content_commitment",
    "key_encipherment",
    "digital_signature",
    "server_auth",
    "client_auth",
    "cert_signing"
```
Most of these are most certainly superfluous, just added in fleeting attempts to resolve the above issue.  

I'm happy to provide the certificate chain, as this is something I've been regularly destroying and regenerating whilst trying to get this working: [here you go](https://gist.github.com/cmacrae/4fd538c3b797b753348f497d53b510ec)

**Comment by cmacrae** [comment]
Hi team - is there anyone that's able to help me with this at all?  
Right now I'm having to rely on LetsEncrypt certificates, which for my configuration, is less than ideal.  

Thanks in advance

**Comment by bahamat** [comment]
@cmacrae In the file you linked, both certificates x509v3 basic constraints have `CA:FALSE`.

Secondly, I hate to be the bearer of bad news, but you included a secret key in that file. While it is a secret gist, this is a public bug with a link to it and it has likely been discovered by bots. You should probably discontinue use of that key.

**Comment by cmacrae** [comment]
@bahamat Ah the `CA:FALSE` parameter would be the reason then! Thank you :) And not to worry about the secret key being published. I did this knowingly - these were freshly generated for the sake of my response, so that secret key and these certs aren’t actually in use anywhere.

I should get some time to look at this again tomorrow - so I’ll give it another shot, ensuring I’ve got the params set up properly, and report back 👍
