### ISSUE TITLE
Dedicated server to deliver product photography with CloudFlare CDN

### ISSUE THREAD

**Issue by dylannirvana** [joyent/triton#249]
We want to use Joyent as a dedicated product image (meaning photography) server for our e-commerce websites, https://www.circalighting.com and https://www.clarksonlighting.com . There are some 30,000+ product photographs, on these web properties. We are currently serving the site from AWS with an integrated (or partially dedicated) server for these product images. My understanding is that using Joyent, they could be delivered faster and cheaper. (Am I correct?!)

We are currently using AWS to serve the images AND the site (on separate instances - but I am not sure that this is what you would call a "dedicated image server". Then these are on CloudFront as CDN

What I want to do is have a Dedicated (product) image server on Joyent, and use CloudFlare as CDN/proxy.

The question is this: what are the best choices in provisioning for this particular use-case? I could not find this published on your site. (Sorry if I missed it somewhere).

Anoop from Corra is working with me on this; and in fact there may be another ticket he opened to discuss. 

Again, what stack is best for a dedicated server to deliver product photography with CloudFlare CDN?
Dylan

**Comment by bahamat** [comment]
Closing this. No feedback from user.
