### ISSUE TITLE
Typo on README.md where physical install indicates COAL download

### ISSUE THREAD

**Issue by liv3010m** [joyent/triton#252]
Hi everyone,

At the install section, when it talks on about doing a Physical install from USB (and not COAL) it indicates to download the coal image (coal-latest.tgz) instead of the USB image (usb-latest.tgz).

Best,
Olivia

> Install
> To install Triton, first download the latest release image:
> 
> curl -C - -O https://us-east.manta.joyent.com/Joyent_Dev/public/SmartDataCenter/coal-latest.tgz
> Once you have downloaded the latest release image, you will need to write it to a USB key boot the head node server using the USB key, and follow the install prompts. All steps necessary to plan, install, and configure Triton DataCenter (Triton) are available in the Joyent customer documentation Installing Triton Elastic Container Infrastructure.

**Comment by bahamat** [comment]
https://cr.joyent.us/6109

**Comment by bahamat** [comment]
Fixed in commit 70baf55.
